package at.ac.tuwien.sepm.groupphase.backend.repository.fitnessComponents;

import at.ac.tuwien.sepm.groupphase.backend.entity.Dude;
import at.ac.tuwien.sepm.groupphase.backend.entity.TrainingSchedule;
import at.ac.tuwien.sepm.groupphase.backend.entity.compositeKeys.TrainingScheduleKey;
import org.springframework.dao.DataAccessException;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;
import java.util.NoSuchElementException;
import java.util.Optional;
import java.util.List;

@Repository
public interface ITrainingScheduleRepository extends JpaRepository<TrainingSchedule, TrainingScheduleKey> {

    /**
     * @param trainingSchedule to be saved in the database
     * @return the saved TrainingSchedule
     * @throws DataAccessException if an error occurred while trying to save the TrainingSchedule in the database
     */
    TrainingSchedule save(TrainingSchedule trainingSchedule) throws DataAccessException;

    /**
     * @param id of TrainingSchedule to be found
     * @return TrainingSchedule found with the given id
     * @throws DataAccessException if an error occurred while trying to find the TrainingSchedule in the database
     */
    @Query("SELECT t FROM TrainingSchedule t WHERE t.id=?1 AND t.isHistory=false")
    TrainingSchedule findById(long id) throws DataAccessException;

    /**
     * @param id of TrainingSchedule to be found
     * @param version of TrainingSchedule to be found
     * @return TrainingSchedule found with the given id and version
     * @throws NoSuchElementException if an error occurred while trying to find the TrainingSchedule in the database
     */
    Optional<TrainingSchedule> findByIdAndVersion(Long id, Integer version) throws NoSuchElementException;

    /**
     * @param id of TrainingSchedule to be deleted
     * @throws DataAccessException if an error occurred while trying to delete the TrainingSchedule in the database
     */
    @Modifying
    @Transactional
    @Query("UPDATE TrainingSchedule t SET t.isHistory=true WHERE t.id=:id AND t.isHistory=false")
    void delete(@Param("id")long id) throws DataAccessException;

    /**
     * @param myId -> ID of the TrainingSchedule that is updated
     * @param dbId -> ID of the TrainingSchedule generated by the database automatically
     * @throws DataAccessException if an error occurred while trying to update the TrainingSchedule in the database
     */
    @Modifying
    @Transactional
    @Query("UPDATE TrainingSchedule t SET t.id=:myID WHERE t.id=:dbID AND t.isHistory=false")
    void updateNew(@Param("myID")long myId, @Param("dbID")long dbId) throws DataAccessException;

    /**
     * @param name of the TrainingSchedules to find
     * @return TrainingSchedules with name beginning with the given name-string
     * @throws DataAccessException if an error occurred while trying to find the TrainingSchedules in the database
     */
    @Query("SELECT t FROM TrainingSchedule t WHERE t.name LIKE ?1% AND t.isHistory=false AND t.isPrivate=false")
    List<TrainingSchedule> findByName(String name) throws DataAccessException;

    /**
     * @param name of the TrainingSchedules to find
     * @param dude that called the method
     * @return TrainingSchedules with name beginning with the given name-string
     * @throws DataAccessException if an error occurred while trying to find the TrainingSchedules in the database
     */
    @Query("SELECT t FROM TrainingSchedule t WHERE t.name LIKE ?1% AND t.isHistory=false AND t.isPrivate=true AND t.creator=?2")
    List<TrainingSchedule> findOwnPrivateByName(String name, Dude dude) throws DataAccessException;

    /**
     * @param filter of the name or description TrainingSchedules to find
     * @param difficulty of TrainingSchedules to find
     * @param intervalLength of TrainingSchedules to find
     * @return TrainingSchedules with given parameters
     * @throws DataAccessException if an error occurred while trying to find the TrainingSchedules in the database
     */
    @Query("SELECT t FROM TrainingSchedule t WHERE (t.name LIKE %?1% OR t.description LIKE %?1%) AND t.difficulty=?2 " +
        "AND t.intervalLength=?3 AND t.isHistory=false AND t.isPrivate=false ORDER BY t.id")
    List<TrainingSchedule> findByFilterWithDifficultyAndInterval(String filter, Integer difficulty, Integer intervalLength) throws DataAccessException;

    /**
     * @param filter of the name or description TrainingSchedules to find
     * @param difficulty of TrainingSchedules to find
     * @return TrainingSchedules with given parameters
     * @throws DataAccessException if an error occurred while trying to find the TrainingSchedules in the database
     */
    @Query("SELECT t FROM TrainingSchedule t WHERE (t.name LIKE %?1% OR t.description LIKE %?1%) AND t.difficulty=?2 " +
        "AND t.isHistory=false AND t.isPrivate=false ORDER BY t.id")
    List<TrainingSchedule> findByFilterWithDifficulty(String filter, Integer difficulty) throws DataAccessException;

    /**
     * @param filter of the name or description TrainingSchedules to find
     * @param intervalLength of TrainingSchedules to find
     * @return TrainingSchedules with given parameters
     * @throws DataAccessException if an error occurred while trying to find the TrainingSchedules in the database
     */
    @Query("SELECT t FROM TrainingSchedule t WHERE (t.name LIKE %?1% OR t.description LIKE %?1%) AND t.intervalLength=?2 " +
        "AND t.isHistory=false AND t.isPrivate=false ORDER BY t.id")
    List<TrainingSchedule> findByFilterWithInterval(String filter, Integer intervalLength) throws DataAccessException;

    /**
     * @param filter of the name or description TrainingSchedules to find
     * @return TrainingSchedules with given parameters
     * @throws DataAccessException if an error occurred while trying to find the TrainingSchedules in the database
     */
    @Query("SELECT t FROM TrainingSchedule t WHERE (t.name LIKE %?1% OR t.description LIKE %?1%) AND t.isHistory=false " +
        "AND t.isPrivate=false ORDER BY t.id")
    List<TrainingSchedule> findByFilterWithoutDifficultyAndInterval(String filter) throws DataAccessException;

    /**
     * @param filter of the name or description TrainingSchedules to find
     * @param difficulty of TrainingSchedules to find
     * @param intervalLength of TrainingSchedules to find
     * @param dude that called the method
     * @return TrainingSchedules with given parameters
     * @throws DataAccessException if an error occurred while trying to find the TrainingSchedules in the database
     */
    @Query("SELECT t FROM TrainingSchedule t WHERE (t.name LIKE %?1% OR t.description LIKE %?1%) AND t.difficulty=?2 " +
        "AND t.intervalLength=?3 AND t.isHistory=false AND t.isPrivate=true AND t.creator=?4 ORDER BY t.id")
    List<TrainingSchedule> findOwnPrivateByFilterWithDifficultyAndInterval(String filter, Integer difficulty, Integer intervalLength, Dude dude) throws DataAccessException;

    /**
     * @param filter of the name or description TrainingSchedules to find
     * @param difficulty of TrainingSchedules to find
     * @param dude that called the method
     * @return TrainingSchedules with given parameters
     * @throws DataAccessException if an error occurred while trying to find the TrainingSchedules in the database
     */
    @Query("SELECT t FROM TrainingSchedule t WHERE (t.name LIKE %?1% OR t.description LIKE %?1%) AND t.difficulty=?2 " +
        "AND t.isHistory=false AND t.isPrivate=true AND t.creator=?3 ORDER BY t.id")
    List<TrainingSchedule> findOwnPrivateByFilterWithDifficulty(String filter, Integer difficulty, Dude dude) throws DataAccessException;

    /**
     * @param filter of the name or description TrainingSchedules to find
     * @param intervalLength of TrainingSchedules to find
     * @param dude that called the method
     * @return TrainingSchedules with given parameters
     * @throws DataAccessException if an error occurred while trying to find the TrainingSchedules in the database
     */
    @Query("SELECT t FROM TrainingSchedule t WHERE (t.name LIKE %?1% OR t.description LIKE %?1%) AND t.intervalLength=?2 " +
        "AND t.isHistory=false AND t.isPrivate=true AND t.creator=?3 ORDER BY t.id")
    List<TrainingSchedule> findOwnPrivateByFilterWithInterval(String filter, Integer intervalLength, Dude dude) throws DataAccessException;

    /**
     * @param filter of the name or description TrainingSchedules to find
     * @param dude that called the method
     * @return TrainingSchedules with given parameters
     * @throws DataAccessException if an error occurred while trying to find the TrainingSchedules in the database
     */
    @Query("SELECT t FROM TrainingSchedule t WHERE (t.name LIKE %?1% OR t.description LIKE %?1%) AND t.isHistory=false " +
        "AND t.isPrivate=true AND t.creator=?2 ORDER BY t.id")
    List<TrainingSchedule> findOwnPrivateByFilterWithoutDifficultyAndInterval(String filter, Dude dude) throws DataAccessException;

}
